[gui]
enable = true
source = gui
size = 700
pos = 50,50

[world]
length = 20

[wesen]
sources = Dwarf,Nightwatch
count = 4
energy = 800
maxage = 250

[food]
count = 30
energy = 50
maxamount = 1000
maxage = 500
growrate = 0.2
seedrate = 0.002

[range]
look = 20
closer_look = 20
talk = 16
seed = 10

[time]
init = 25
max = 50
look = 1
closerlook = 2
move = 7
eat = 10
talk = 1
vomit = 12
broadcast = 1
attack = 14
donate = 13
reproduce = 20
